/**
 * Validates MCQ output generated by the AI
 * Ensures strict format and correct question count
 */

function validateMCQOutput(output, expectedCount) {
  if (!output || typeof output !== "string") {
    return {
      valid: false,
      error: "Output is empty or not a string"
    };
  }

  // Regex for ONE MCQ block
  const mcqBlockRegex =
    /Q\d+\.\s.+?\nA\.\s.+?\nB\.\s.+?\nC\.\s.+?\nD\.\s.+?\nCorrect Answer:\s[ABCD]/gs;

  const matches = output.match(mcqBlockRegex);

  if (!matches) {
    return {
      valid: false,
      error: "No valid MCQ blocks found"
    };
  }

  if (expectedCount && matches.length !== expectedCount) {
    return {
      valid: false,
      error: `Expected ${expectedCount} questions, but found ${matches.length}`
    };
  }

  return {
    valid: true,
    questionCount: matches.length
  };
}

module.exports = { validateMCQOutput };
